steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-docker.pkg.dev/${PROJECT_ID}/cicd-demo/frontend', '.']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'cicd-demo', '--image', 'europe-docker.pkg.dev/${PROJECT_ID}/cicd-demo/frontend', '--region', 'europe-west1']
images:
  - 'europe-docker.pkg.dev/${PROJECT_ID}/cicd-demo/frontend'
