steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-docker.pkg.dev/${PROJECT_ID}/cicd-demo/frontend', './cicd_demo']
images:
  - 'europe-docker.pkg.dev/${PROJECT_ID}/cicd-demo/frontend'